// Writes src/stats.ts from the live subgraph and mirror node so no figure in the composition
// is typed by hand. Runs before every render. The spoken figures in vo-gen.js (v03) are words
// and cannot update themselves: re-read them against this output before regenerating narration.
const fs = require('fs');
const SUBGRAPH = process.env.SUBGRAPH_URL || 'http://38.49.213.208:8100/subgraphs/name/aetheris';
const TOPIC = '0.0.10518320';
const AGENCY = '0x16fA9CC838Ab5380F0Ebe3C261a2F57E0FBAbc81';
const TREASURY = '0x10360383a6b43Fd22BE257bE334E9A9ad83B5598';
const WORKER = '0xBC9dD5CB75219d764ed74021FeF6e50dbF682541';

(async () => {
  const q = `{ jobs(first: 200) { jobId status specURI deposit tasks { status fee role subAgent { id } } }
    settlements(first: 200) { viaHts amount subAgent { id } } subAgents(first: 100) { id tasksCompleted totalEarned }
    _meta { block { number } } }`;
  const res = await fetch(SUBGRAPH, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ query: q }) });
  const { data } = await res.json();
  const jobs = data.jobs, st = data.settlements, agents = data.subAgents;
  const mirror = await (await fetch(`https://testnet.mirrornode.hedera.com/api/v1/topics/${TOPIC}/messages?limit=1&order=desc`)).json();
  const worker = agents.find((a) => a.id.toLowerCase() === WORKER.toLowerCase());
  const stats = {
    fetchedAt: new Date().toISOString(),
    block: Number(data._meta.block.number),
    jobs: jobs.length,
    settledJobs: jobs.filter((j) => j.status === 'Settled').length,
    briefJobs: jobs.filter((j) => j.specURI.startsWith('hcs://')).length,
    tasks: jobs.reduce((n, j) => n + j.tasks.length, 0),
    paidTasks: jobs.reduce((n, j) => n + j.tasks.filter((t) => t.status === 'Paid').length, 0),
    settlements: st.length,
    htsSettlements: st.filter((s) => s.viaHts).length,
    erc20Settlements: st.filter((s) => !s.viaHts).length,
    paidToSubAgentsUsd: st.reduce((n, s) => n + Number(s.amount), 0) / 1e6,
    subAgents: agents.length,
    workerTasks: worker ? Number(worker.tasksCompleted) : 0,
    workerEarnedUsd: worker ? Number(worker.totalEarned) / 1e6 : 0,
    roles: [...new Set(jobs.flatMap((j) => j.tasks.map((t) => t.role)))].sort(),
    hcsLatestSequence: Number(mirror.messages[0].sequence_number),
    topic: TOPIC, agency: AGENCY, treasury: TREASURY, worker: WORKER,
  };
  fs.mkdirSync('src', { recursive: true });
  fs.writeFileSync('src/stats.ts', '// Generated by fetch-stats.js from the live subgraph and mirror node. Do not edit by hand.\n' +
    `export const STATS = ${JSON.stringify(stats, null, 2)} as const;\n`);
  console.log(JSON.stringify(stats, null, 2));
})().catch((e) => { console.error('fetch-stats failed:', e.message); process.exit(1); });
